dist: trusty
sudo: required
language: java
jdk:
  - oraclejdk8
services:
  - docker

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

matrix:
  include:
  - name: "AllUnitTests"
    before_install:
      - docker run -d -p 3307:3306 -e MYSQL_ROOT_PASSWORD=massagerelax -e MYSQL_USER=massagerelax -e MYSQL_DATABASE=massagerelax -e MYSQL_PASSWORD=massagerelax --name mysql_massagerelax mysql:5.7.23
    script: travis_wait 20 ./gradlew test -Dspring.datasource.url=jdbc:mysql://localhost:3307/massagetrelax?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false

install: travis_retry ./gradlew assemble

after_success:
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  - |
    if [ "$TRAVIS_BRANCH" = master ]; then
      ./gradlew build releaseDocker -PcustomTagVersion=latest -x test;
    else
      tag_name=`echo $TRAVIS_BRANCH | tr / - `;
      ./gradlew build releaseDocker -PcustomTagVersion=$tag_name -x test;
    fi

before_install:
  # troubleshooting info in case of problems
  - docker version
  - docker info
